#+title: Arrays
An array and a couple of examples of its use:
#+begin_src javascript
const t = [1, -1, 3]

t.push(5)

console.log(t.length) // 4 is printed
console.log(t[1])     // -1 is printed

t.forEach(value => {
  console.log(value)  // numbers 1, -1, 3, 5 are printed, each on its own line
})
#+end_src

Notable in this example is the fact that although a variable declared with =const= cannot be reassigned to a different value, the contents of the object it references can still be modified. This is because the =const= declaration ensures the immutability of the reference itself, not the data it points to. Think of it like changing the furniture inside a house, while the address of the house remains the same.

One way of iterating through the items of the array is using =forEach= as seen in the example. =forEach= receives a function defined using the arrow syntax as a parameter.
#+begin_src javascript
value => {
  console.log(value)
}
#+end_src 
forEach calls the function for each of the items in the array, always passing the individual item as an argument. The function as the argument of forEach may also receive other arguments.

In the previous example, a new item was added to the array using the method push. When working with arrays, techniques from functional programming are often used. One characteristic of the functional programming paradigm is the use of immutable data structures. it is preferable to use the method concat, which creates a new array with the added item. This ensures the original array remains unchanged.
#+begin_src javascript
const t = [1, -1, 3]

const t2 = t.concat(5)  // creates new array

console.log(t)  // [1, -1, 3] is printed
console.log(t2) // [1, -1, 3, 5] is printedcopy
#+end_src 
The method call =t.concat(5)= does not add a new item to the old array but returns a new array which, besides containing the items of the old array, also contains the new item.

There are plenty of useful methods defined for arrays. Let's look at a short example of using the map method.

#+begin_src javascript
const t = [1, 2, 3]

const m1 = t.map(value => value * 2)
console.log(m1)   // [2, 4, 6] is printed
#+end_src 
Based on the old array, map creates a new array, for which the function given as a parameter is used to create the items. In the case of this example, the original value is multiplied by two.

Map can also transform the array into something completely different:

#+begin_src javascript
const m2 = t.map(value => '<li>' + value + '</li>')
console.log(m2)  
// [ '<li>1</li>', '<li>2</li>', '<li>3</li>' ] is printed
#+end_src

Here an array filled with integer values is transformed into an array containing strings of HTML using the map method.

Individual items of an array are easy to assign to variables with the help of the destructuring assignment.
#begin_src javascript
const t = [1, 2, 3, 4, 5]

const [first, second, ...rest] = t

console.log(first, second)  // 1 2 is printed
console.log(rest)          // [3, 4, 5] is printed
#+end_src
Above, the variable first is assigned the first integer of the array and the variable second is assigned the second integer of the array. The variable rest "collects" the remaining integers into its own array.